name: Benchmarks
on:
  workflow_dispatch:
  push:

jobs:
  Benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        framework: [net7.0, net6.0, net48]
        platform: [x64]
        configuration: [Release]
        exclude:
          - os: ubuntu-latest
            framework: net48
          - os: ubuntu-latest
            framework: net461
          - os: macos-latest
            framework: net48
          - os: macos-latest
            framework: net461
    env:
      project_path: './src/BenchmarkPlayground/BenchmarkPlayground.csproj'
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Disable .NET SDK Telemetry and Logo
        run: |
          echo "DOTNET_NOLOGO=1" | Out-File -FilePath  $env:GITHUB_ENV -Encoding utf8 -Append
          echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" | Out-File -FilePath  $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        if: ${{ startswith(matrix.framework, 'net6.') }}

      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          
      - run: |
          $benchmark_results_artifact_name = "benchmarkresults_${{matrix.os}}_${{matrix.framework}}_${{matrix.platform}}_${{matrix.configuration}}"
          $working_directory = "$env:GITHUB_WORKSPACE"
          Write-Host "Results Artifact Name: $benchmark_results_artifact_name"
          Write-Host "Working Directory: $working_directory"
          echo "benchmark_results_artifact_name=$benchmark_results_artifact_name" | Out-File -FilePath  $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh
      - run: dotnet build ${{env.project_path}} --configuration ${{matrix.configuration}} --framework ${{matrix.framework}}
      - run: './src/BenchmarkPlayground/bin/${{matrix.configuration}}/${{matrix.framework}}/BenchmarkPlayground.exe'
      # upload reports as build artifacts
      - name: Upload Benchmark Artifacts
        uses: actions/upload-artifact@v2
        if: ${{always()}}
        with:
          name: '${{env.benchmark_results_artifact_name}}'
          path: '${{github.workspace}}/src/BenchmarkPlayground/bin/${{matrix.configuration}}/${{matrix.framework}}/BenchmarkDotNet.Artifacts/'